### ISSUE TITLE
topページの提案

### ISSUE THREAD

**Issue by kehonda** [dearasus/blog_app#4]
# 現状
- `/articles/:id`にリダイレクトしている
    - ブログサービスっぽくない

# 提案
- `/`は記事一覧を作ってみよう
- title/user名/contentがちょっと見える

# やってほしいこと
- 簡単なmockを紙などでつくる
- 工数出し
- 作業

**Comment by dearasus** [comment]
# 工数出し(相対ポイント)
topcontroller#indexアクションを定義する(2pt)
ユーザ名を表示するindex.html.erbを作る(2pt)
