### ISSUE TITLE
userページの新設

### ISSUE THREAD

**Issue by kehonda** [dearasus/blog_app#5]
# 現状
- ユーザーページがないので、ブログサービス感がない

# 提案
- `/users/:id`ページを作ってみよう
   - ユーザ名や、そのユーザが書いた記事一覧が表示されてる

# やってほしいこと
- 簡単なmockを紙などでつくる
- 工数出し
- 作業

**Comment by dearasus** [comment]
# 工数出し(相対ポイント)
userscontroller#showを書く(2pt)
viewの変更(2pt)
